**Student #1**

In [1]:
# Question 3
html_doc = '''
<table border="0">
       <thead>
            <tr><th>Option Required Courses</th><th>&nbsp;</th></tr>
       </thead>
       <tbody>
            <tr>
              <td data-title="ISOM-IS Courses">ISOM 4100 - <span>Information Systems Auditing</span></td>
              <td data-title="General Req.">3 credits</td>
           </tr>
           <tr>
              <td data-title="ISOM-IS Courses">ISOM 4300 - <span>Information Systems Control and Assurance</span></td>
              <td data-title="General Req.">3 credits</td>
           </tr>
           <tr>
<td data-title="ISOM-IS Courses"><strong>Extra courses/credits for ISA Option</strong></td>
<td data-title="General Req.">2 courses (6 credits)</td>
           </tr>
       </tbody>
</table>'''

out_html = html_doc.splitlines()
tdLines = []
lineTxt = []
for idx, line in enumerate(out_html):
   if "td" in line:
      #print(f"[{idx}] {line}")
      tdLines.append(line.strip())

#line breaker
print("=====================================")
x = []
courses = {}
for line in tdLines:
   print("line: ", line)
   search = True
   while search:
      if line.find(">") > 0:
         start = line.find(">") +1
         end = line.find("<",line.find(">"))

         #find string
         string = line[start:end].replace("credits","").strip("- !")
         if len(string) > 0:
            print("result:",string)
            x.append(string)

         #delete unnecessary
         line = line[start:]
         print("Update: ",line)
      else:
         search = False


#courtesy to https://stackoverflow.com/questions/2597166/make-dictionary-from-list-with-python/2597178#2597178
#for the list comprehension ---> dict(x[i:i+2] for i in range(0, len(x), 2))
#but I'm not sure is this the right way to reference others' code
courses = list(tuple(x[i:i+2])for i in range(0, len(x), 3) if i+2<len(x))
credits = x[2::3]

#combine lists
answer = dict(zip(courses,credits))
print("============================================")
print("The dict is",answer)


# %%

=====================================
line:  <td data-title="ISOM-IS Courses">ISOM 4100 - <span>Information Systems Auditing</span></td>
result: ISOM 4100
Update:  ISOM 4100 - <span>Information Systems Auditing</span></td>
result: Information Systems Auditing
Update:  Information Systems Auditing</span></td>
Update:  </td>
Update:
line:  <td data-title="General Req.">3 credits</td>
result: 3
Update:  3 credits</td>
Update:
line:  <td data-title="ISOM-IS Courses">ISOM 4300 - <span>Information Systems Control and Assurance</span></td>
result: ISOM 4300
Update:  ISOM 4300 - <span>Information Systems Control and Assurance</span></td>
result: Information Systems Control and Assurance
Update:  Information Systems Control and Assurance</span></td>
Update:  </td>
Update:
line:  <td data-title="General Req.">3 credits</td>
result: 3
Update:  3 credits</td>
Update:
line:  <td data-title="ISOM-IS Courses"><strong>Extra courses/credits for ISA Option</strong></td>
Update:  <strong>Extra courses/credits for ISA Option</strong></td>
result: Extra courses/ for ISA Option
Update:  Extra courses/credits for ISA Option</strong></td>
Update:  </td>
Update:
line:  <td data-title="General Req.">2 courses (6 credits)</td>
result: 2 courses (6 )
Update:  2 courses (6 credits)</td>
Update:
============================================
The dict is {('ISOM 4100', 'Information Systems Auditing'): '3', ('ISOM 4300', 'Information Systems Control and Assurance'): '3'}

**Student #2**

In [ ]:
#%%
# Question 3
html_doc = '''
<table border="0">
       <thead>
            <tr><th>Option Required Courses</th><th>&nbsp;</th></tr>
       </thead>
       <tbody>
            <tr>
              <td data-title="ISOM-IS Courses">ISOM 4100 - <span>Information Systems Auditing</span></td>
              <td data-title="General Req.">3 credits</td>
           </tr>
           <tr>
              <td data-title="ISOM-IS Courses">ISOM 4300 - <span>Information Systems Control and Assurance</span></td>
              <td data-title="General Req.">3 credits</td>
           </tr>
           <tr>
<td data-title="ISOM-IS Courses"><strong>Extra courses/credits for ISA Option</strong></td>
<td data-title="General Req.">2 courses (6 credits)</td>
           </tr>
       </tbody>
</table>
''' 
output_html = html_doc.splitlines() #output_html is still a string

extracted_info = []
new_dict = {}

for line in output_html: #parse each line 
   if "td" and "ISOM 4" in line: 
      extracted_info = line.strip(" ").replace('<td data-title="ISOM-IS Courses">',"").replace(' <span>',"").replace('</span></td>',"").strip(' ').split(" -") #get away the excessive information in that specific line, and split ISOM xxxx and course name
      for item in extracted_info: #extracted_info will store ["ISOM4100", "Information System Auditing", "ISOM4300", "Information Systems Control and Assurance"]
         if "ISOM" in item: 
            new_dict.update({item:extracted_info[1]}) 
  
print (new_dict)


# %%

**Modified**

In [ ]:
# From Step 1
html_doc = """<table border="0">
       <thead>
            <tr><th>Option Required Courses</th><th>&nbsp;</th></tr>
       </thead>
       <tbody>
            <tr>
              <td data-title="ISOM-IS Courses">ISOM 4100 - <span>Information Systems Auditing</span></td>
              <td data-title="General Req.">3 credits</td>
           </tr>
           <tr>
              <td data-title="ISOM-IS Courses">ISOM 4300 - <span>Information Systems Control and Assurance</span></td>
              <td data-title="General Req.">3 credits</td>
           </tr>
           <tr>
<td data-title="ISOM-IS Courses"><strong>Extra courses/credits for ISA Option</strong></td>
<td data-title="General Req.">2 courses (6 credits)</td>
           </tr>
       </tbody>
</table>
"""

html_list = html_doc.splitlines()

# From Step 2
new_list = []
for item in html_list:
    if "td" in item and "ISOM " in item:
            course = item.replace('<td data-title="ISOM-IS Courses">',"")
            course = course.replace('<span>',"")
            course = course.replace('</span></td>',"")
            new_list.append(course)


# From Step 3
output_dict = {}
for num, item in enumerate(new_list):
    list1 = item.split(" - ")
    course_code = "".join(list1[0].split())
    course_code = course_code.replace(" ", "")
    output_dict[course_code] = list1[1]

print(output_dict)    

# %%

# Part 2: 3 credits
# Extract number of credits from the data fragment
credit_list = []

for item in html_list:
    if " credits<" in item:
        credit = item.replace('<td data-title="General Req.">',"")
        credit = credit.replace('credits</td>',"")
        credit = credit.replace(" ","")
        credit = int(credit)
        credit_list.append(credit)


# %%

# Convert output_dict into list of tuples
new_list1 = [(course_code,course_name) for course_code,course_name in output_dict.items()]

# Assign to dictionary
final_dict = {course: credit for (course, credit) in zip(new_list1, credit_list)}

print(final_dict)